language: c
compiler: gcc

os:
- linux
- osx

env:
  jobs:
  - MRUBY_VERSION=1.4.1
  - MRUBY_VERSION=2.0.1
  - MRUBY_VERSION=2.1.0
  global:
  - secure: "xpNOMMQlTV7XA7iXBtlOQinncjXYHtIDV72/aL5tkSRc62Usu47VasFFPN/u/TPRSkJSjcl+vpZ2HBcZtPXepuKy3o0cel2NgCAvFVkh4bc49K7WhSJxMW4FK/9cThUYfTpejBs2AaSQF8Xh6H6EtYQ6I2pUz8cT2m51JIaxMWOt4txgY69S/ada0FAA0y56ocWI5MeNzQdu6Md2uihQgnagrUYwxG+KGY27j3Agw4KXBjUf2MvV/fHXhhmGSoVEvj0FjAeV6ySnvnuJc5O6XXlOJyCGydZYyNIQ9L9j72bKKCpwWWhvH/Is9tpF1Q/vypaInSjYYtENWMroyJ6NA2d4T0TcB2snPEpTMYkwD301Fi8UEN1VAVNZZSaMyp+TffqS6NMPn5a0N0wy4rcRqD64ZAVidgkK39GuBBBwHZ3yvCiS+s7KEbZVpxE336Fa9E5qoW6ccMkzZpvJcXRBEUdsU5+b0m+1oob6MVqiXe9EUF/IXdzt10CpWoZoX6VvSu/3KJqnApL2Ki8t77M9wrWZMilFwmvqQi+rMg+kklLIEZOMmr829azbihRRMsGnTTOYj3nq+VNAQHKjOusLKeKjZm/+rs7ZOs4p3Co2+o+ocW1EEoWiAzJaUjx3jwHLCX1TP6PSHTNMhl4jlfQdwMV+Jfa772TDDNRcdDVWT6k="
  - secure: "0ZbKFsnJvDU5D4zlWZ4usoUj/1Bgflm4+UNejstdHyZlQmtV4PT+Z6tddtf/aiF/gk00PlHC4iHke+M9JxfemhxfgyqL2mYzzSxrY5isPe17X921OnAlFfW4w4hCZB6de05aqGM9E5P/TPlCgML8EMZZ96N5fR6yDHJmCH1y1KQQNAQ+gThclNyRtw+kgFCgNViiHlLIlG/0S2Iq8flFaVBRY+Q+aD8QR8RAjglsmS0flqFfXSpJAYiLZIWpit26+529P37kJxLkQ/Eyjd4Nz4GkDm6Auzif5KkeQBjyITiy8OlhxL3LaX6tn3Qk5cvWbnrFubwyG3vRyYYupuZB5VNcIOykmGmXG7ZUN8/qOVTzIWbhUiTYQRE5MaiFNjXpUWsMLRzZggld93/OkF1wibXrGtjJv73/oMixt0M3Wc/xiLOtWpXiE83UiIS1w8gk58PlOYYdduTt/2SXgqjeQYYNyTYnU1bLOVxhURli0jxskqgs+77vgtysf9he+vJW+OMdUz33p8HjjNk4joxqYD/UPr8CBMZHTmqurJkvgmUwuJ2EH89MlNAUyObJ7nGg4Bh6wbBw99lf33JPLPkCCYP072rdk7A+WyFMDsgUCPj9eNvcbLZIZpO2FbSQglrvCaXN9UbHZjLZK2smlhvRRm2PeaD9syxLReZNumn9bok="
  - secure: "JDWRBaf1zAuQ0jjteK3GHnuumZw8NzbC5VB6HVlRrBNJl8DHkuk4DDav5zBtoXA01M17Dfo+rNP8MkAjpUsyXaL1MykJWcq5LFMKsfSJXeJaMLtwBbo+DU2n6pT50kpQ1uP2dAfC5lLsCPeTojOJw3qfCPw+fhcSMrlEraA4+cnfWiHJ058ICHzKmtkxf31Srcf/feJgmRbPjGGL4M0Rxg3fbTPNgHl9EOjUdFEV6t+bm+PaZHhRekNa/Fx1Dt0r2dEIFk+qkjgeqZZdALZdekEfxhwbB2pVkLeytycp7UBD3B/HjU0JL5NiCPZnfsNspHPBaMVzMEcLM8XmnpJL05E+fH+usSsSShPjFGc0K3dTyuT+6oTg3Wo0okCuJpE8pmge/XPtHvFiFb9ffGRqlZromgKikyTKICQK5SPod1ooIZYC+PHq47dgluQICpVcnXFKVPHx+fqUS+BiE33SzxeVTtcTJOZET3oNevzgmjpl/RLBBhM74mPf5A2ntMk4r/hiQfX3f72w6qNqrTtQKPmyNS1/LVFAcgYLNGuZuSdng17YXhL8KEjsUZMecgHndWwgaujlVQyhjvlTxYsThkfxVfLhRZh1IGC5XdCOv93/rUae4il27qS97qtWrhfhoU5fO3psROenPhiR5zlJvdvxXFTWz6kq9OAaEVQQ7wA="
  - secure: "Q9kpQnsyXBaeC39Y9OQkAXXMHdP4o/6PPkgnQ6fV5aH0tInsjCm4O9k149x5jO5i9WaoOLRq0D8TlhBu8ys71U3wdWs0jhL9YG8O0oXGLCwKO21vgwiWXInuKZtk+XldMJi48zYh7JFh+IGQdGbLTC56mC60O/cwGsGvkvqL6U0wvR9hRhOaAnZeFL1euFDE7I/KnGGF++2ihxAuawYXqw035uo9uVGGLcnNru4PaQGRZMPHngt2mOx+hXJ6Sl4z/VhNiZHN2rvjin99v1xhWlWKuM8eFWiiCUVYzhetiakiInkOGqO4I7h3gc4+STXc/NO+/pBMFCIcsbfndbIWL5s44LwstuVNnun++vGCheNHNq2qyglq/DvEndsbmpjn6spA4cVdItNM75/XZVlN4BqIK2ae0aULt/IFTLhiNYx2ha3lZ49k8SLMNiNc7StUUzfKfPQQnaAPSLq5oadA1JgwbzhJqUz7WVn3IY2Ax+R0QEWHpNuTW60MhRES8AJqs7p/K/0U7Qmsckv86sk8FJWDzFOR4r0+QpVFKTdjxD6GpVzJ3ulLxr95O3EDuOwBYMXge2IbVzBhvb5dLe6pbjBjHPRnX9ishumNkABj9TKSifhUkSIQo+e7kqtXD4WqwilM9taWXm1EHgZ1ON1owuh5jsnhubWz+M6LHERhTfU="
  - secure: "CeeHoP658PItTX5OnhnXXWhyS70VDBgfZOO0Ex/8tamr0wEJbl3Z7z7QIWRxu75fV17fQjUtqKZknyHjHcFNc+Ug47bWgkijxlREjgvxe7p3pak8TP4o1XgRqaY75N5aZRCPpgLP6pj7pwiHgkeqZnUHCRZi5tjgVTqwbXCywjmnT15zwcN3FnHgio4KgO7glD+zvo49lhbPb9/4rOtPgPTKPM0ISAr4MeiSr+XtQgUMel5iA8y64r4H4/Np9CKWyHwI2PgWD/pHODkMkJkEfFzuCfius0v4RsW7P2uwyxVPlc2mtAAkCuo181qKGIq2DgF4N2KZRgCmeXMTM2E9TBmcSF/MDAvzSAJK3cVdfXep3ddcQZWyvFsZ4AO/1Zl0XFJTc6bjWDat3gDbYhl3SwIrAA+pmyIIdP7y8wi2HjddsheyVOu3CJJtNEJ6IhhGz6Oaba6SbzobIuHUhCl6l9YKjIbe02tHU0MMhUlgN3FW1D/swy9Z4wZl6H16fQq2mguOmjmXnm6eLvtoKYKWd3HarUTTpWMxKW/jPy0jb6yCh/oDr0Oj4/cLm6t3BZpvihVJjfmll7g/7x4rluez9c4+jAlkqh6oC6ScwMazcXJPgxOFPIw3fXJM46MlUbmHaaYiKeRhoxGF2EznldX5KzlFUFfSin5FutngvAUPrJk="

addons:
  apt:
    packages:
    - gcc-multilib
    - lib32readline-dev
    - lib32ncurses5-dev

before_script:
- openssl aes-256-cbc -K $encrypted_185d3ff9ea72_key -iv $encrypted_185d3ff9ea72_iv -in id_rsa.uploader.enc -out id_rsa.uploader -d
- chmod 600 id_rsa.uploader

script:
- npm install
- node deploy.js
