language: c
compiler: gcc

os:
  - linux
  - osx

env:
  jobs:
    - MRUBY_VERSION=1.4.1
    - MRUBY_VERSION=2.0.1
    - MRUBY_VERSION=2.1.0

addons:
  apt:
    packages:
    - gcc-multilib

before_script:
  - openssl aes-256-cbc -K $encrypted_185d3ff9ea72_key -iv $encrypted_185d3ff9ea72_iv -in id_rsa.uploader.enc -out id_rsa.uploader -d
  - chmod 600 id_rsa.uploader

script:
  - ruby deploy.rb
