version: 1.0.{build}
image: Visual Studio 2015

environment:
  MRUBY_PLATFORM: win32
  SFTP_HOST:
    secure: YHpE1ic0QlIBvAXdCwjLLpo/3fhSyDVXSpn6RFg+QnI=
  SFTP_PORT:
    secure: 98aae/Sddmh3TUDrLygfAg==
  SFTP_USER: uploader
  SFTP_DEST: /recv
  SFTP_IDENTITY: id_rsa.uploader
  ENC_KEY:
    secure: WgnXNx0FV1BZjJhPLzWLg0nX4VJnCPEIPT0B530Xhm7SkQ+7MiSHOPGYiKeVrlnE/rny1jp1IbBBRUTOjfgFZ21h9eCiJIgyRA9WPxjPIe4=
  ENC_IV:
    secure: jWTt/wb7DSBnpgs0UdUEE+I/GUcF2r6kHG1gewzVy+k16VqRd2mkdLMJcT92NHDt
  matrix:
  -
    MRUBY_VERSION: 1.4.1
    MRUBY_ARCH: x64
    MRUBY_ARCH_WIN: amd64
  -
    MRUBY_VERSION: 1.4.1
    MRUBY_ARCH: ia32
    MRUBY_ARCH_WIN: x86
  -
    MRUBY_VERSION: 2.0.0
    MRUBY_ARCH: x64
    MRUBY_ARCH_WIN: amd64
  -
    MRUBY_VERSION: 2.0.0
    MRUBY_ARCH: ia32
    MRUBY_ARCH_WIN: x86
  -
    MRUBY_VERSION: 2.0.1
    MRUBY_ARCH: x64
    MRUBY_ARCH_WIN: amd64
  -
    MRUBY_VERSION: 2.0.1
    MRUBY_ARCH: ia32
    MRUBY_ARCH_WIN: x86
  -
    MRUBY_VERSION: 2.1.0
    MRUBY_ARCH: x64
    MRUBY_ARCH_WIN: amd64
  -
    MRUBY_VERSION: 2.1.0
    MRUBY_ARCH: ia32
    MRUBY_ARCH_WIN: x86

cache:
- node_modules

build_script:
- cmd: >-
    openssl enc -aes-256-cbc -in %SFTP_IDENTITY%.enc -out %SFTP_IDENTITY% -d -K %ENC_KEY% -iv %ENC_IV%

    set PATH=%PATH%;C:\msys64\usr\bin

    set NODE_OPTIONS=--max-old-space-size=1024

    call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %MRUBY_ARCH_WIN%

    npm start
